apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: streamlit
  name: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: streamlit
    spec:
      containers:
      - image: vinycoolguy/streamlit:latest
        name: streamlit
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: "http://model:8000"
        
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: streamlit
  name: streamlit
spec:
  ports:
  - name: "8501"
    nodePort: 30000
    port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app: streamlit
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: model
  name: model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: model
    spec:
      containers:
      - image: vinycoolguy/house-price-model:latest
        name: house-price-model
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: model
  name: model
spec:
  ports:
  - name: "8000"
    nodePort: 30100
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: model
  type: NodePort

